
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '687E0A0C3AC9A019D06BB1CA713BFE06'
    
_lr_action_items = {'SEPARATOR':([14,15,19,],[17,-3,17,]),'ID':([0,5,6,12,17,],[1,7,8,15,15,]),'LP':([3,10,],[5,12,]),'RB':([8,],[10,]),'QGEN':([9,],[11,]),'RP':([11,14,15,19,],[13,18,-3,-2,]),'LB':([4,],[6,]),'DISPLAY':([0,],[3,]),'EOL':([13,18,],[16,20,]),'ASSIGNMENT':([1,],[4,]),'$end':([2,16,20,],[0,-4,-1,]),'CONCATENATION':([7,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'IDS':([12,17,],[14,19,]),'expression':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> ID ASSIGNMENT LB ID RB LP IDS RP EOL','expression',9,'p_expression_table','syntaxAnalyzer.py',11),
  ('IDS -> IDS SEPARATOR IDS','IDS',3,'p_expression_ids','syntaxAnalyzer.py',16),
  ('IDS -> ID','IDS',1,'p_expression_ids','syntaxAnalyzer.py',17),
  ('expression -> DISPLAY LP ID CONCATENATION QGEN RP EOL','expression',7,'p_expression_display','syntaxAnalyzer.py',23),
]
